INSERT INTO "public".clientes (id, nombre, apellido, email, create_at) VALUES(1, 'Andrés', 'Guzmán', 'profesor@bolsadeideas.com', '2018-01-01');
INSERT INTO "public".clientes (id, nombre, apellido, email, create_at) VALUES(2, 'Mr. John', 'Doe', 'john.doe@gmail.com', '2018-01-02');
INSERT INTO "public".clientes (id, nombre, apellido, email, create_at) VALUES(3, 'Linus', 'Torvalds', 'linus.torvalds@gmail.com', '2018-01-03');
INSERT INTO "public".clientes (id, nombre, apellido, email, create_at) VALUES(4, 'Rasmus', 'Lerdorf', 'rasmus.lerdorf@gmail.com', '2018-01-04');
INSERT INTO "public".clientes (id, nombre, apellido, email, create_at) VALUES(5, 'Erich', 'Gamma', 'erich.gamma@gmail.com', '2018-02-01');
INSERT INTO "public".clientes (id, nombre, apellido, email, create_at) VALUES(6, 'Richard', 'Helm', 'richard.helm@gmail.com', '2018-02-10');
INSERT INTO "public".clientes (id, nombre, apellido, email, create_at) VALUES(7, 'Ralph', 'Johnson', 'ralph.johnson@gmail.com', '2018-02-18');
INSERT INTO "public".clientes (id, nombre, apellido, email, create_at) VALUES(8, 'John', 'Vlissides', 'john.vlissides@gmail.com', '2018-02-28');
INSERT INTO "public".clientes (id, nombre, apellido, email, create_at) VALUES(9, 'Dr. James', 'Gosling', 'james.gosling@gmail.com', '2018-03-03');
INSERT INTO "public".clientes (id, nombre, apellido, email, create_at) VALUES(10, 'Magma', 'Lee', 'magma.lee@gmail.com', '2018-03-04');
INSERT INTO "public".clientes (id, nombre, apellido, email, create_at) VALUES(11, 'Tornado', 'Roe', 'tornado.roe@gmail.com', '2018-03-05');
INSERT INTO "public".clientes (id, nombre, apellido, email, create_at) VALUES(12, 'Jade', 'Doe', 'jane.doe@gmail.com', '2018-03-06');
